//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZHPCMS.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SZHPCMS.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Settings.
        /// </summary>
        public static string ArchiveSettings {
            get {
                return ResourceManager.GetString("ArchiveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banners.
        /// </summary>
        public static string Banners {
            get {
                return ResourceManager.GetString("Banners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Center Polls.
        /// </summary>
        public static string CallCenterPolls {
            get {
                return ResourceManager.GetString("CallCenterPolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canned Emails.
        /// </summary>
        public static string CannedEmails {
            get {
                return ResourceManager.GetString("CannedEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        public static string Careers {
            get {
                return ResourceManager.GetString("Careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Contact To Chairman.
        /// </summary>
        public static string ChairmanContact {
            get {
                return ResourceManager.GetString("ChairmanContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions &amp; Requirements.
        /// </summary>
        public static string ConditionsAndRequirements {
            get {
                return ResourceManager.GetString("ConditionsAndRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Settings.
        /// </summary>
        public static string ContactsSettings {
            get {
                return ResourceManager.GetString("ContactsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Management.
        /// </summary>
        public static string ContentManagement {
            get {
                return ResourceManager.GetString("ContentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Services.
        /// </summary>
        public static string EService {
            get {
                return ResourceManager.GetString("EService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Settings.
        /// </summary>
        public static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ&apos;s.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedBack.
        /// </summary>
        public static string FeedBack {
            get {
                return ResourceManager.GetString("FeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedbacks.
        /// </summary>
        public static string Feedbacks {
            get {
                return ResourceManager.GetString("Feedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Management.
        /// </summary>
        public static string FormManagement {
            get {
                return ResourceManager.GetString("FormManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image/Video Gallery.
        /// </summary>
        public static string Gallary {
            get {
                return ResourceManager.GetString("Gallary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page Settings.
        /// </summary>
        public static string HomePageSettings {
            get {
                return ResourceManager.GetString("HomePageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Applicants.
        /// </summary>
        public static string JobApplicants {
            get {
                return ResourceManager.GetString("JobApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android App Link.
        /// </summary>
        public static string lblAndoidLink {
            get {
                return ResourceManager.GetString("lblAndoidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Logo.
        /// </summary>
        public static string lblAndroidLogo {
            get {
                return ResourceManager.GetString("lblAndroidLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android App QR Image.
        /// </summary>
        public static string lblAndroidQRImage {
            get {
                return ResourceManager.GetString("lblAndroidQRImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Logo.
        /// </summary>
        public static string lblAppLogo {
            get {
                return ResourceManager.GetString("lblAppLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Store URL.
        /// </summary>
        public static string lblAppStoreURL {
            get {
                return ResourceManager.GetString("lblAppStoreURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        public static string lblArabic {
            get {
                return ResourceManager.GetString("lblArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience Arabic.
        /// </summary>
        public static string lblAudienceArabic {
            get {
                return ResourceManager.GetString("lblAudienceArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience English.
        /// </summary>
        public static string lblAudienceEnglish {
            get {
                return ResourceManager.GetString("lblAudienceEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit Arabic.
        /// </summary>
        public static string lblBenefitsAr {
            get {
                return ResourceManager.GetString("lblBenefitsAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits English.
        /// </summary>
        public static string lblBenefitsEn {
            get {
                return ResourceManager.GetString("lblBenefitsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Berry App QR Image.
        /// </summary>
        public static string lblBlackBerryQRImage {
            get {
                return ResourceManager.GetString("lblBlackBerryQRImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Berry World URL.
        /// </summary>
        public static string lblBlackBerryWorldURL {
            get {
                return ResourceManager.GetString("lblBlackBerryWorldURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Industry.
        /// </summary>
        public static string lblCareerIndustry {
            get {
                return ResourceManager.GetString("lblCareerIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Type.
        /// </summary>
        public static string lblCareerType {
            get {
                return ResourceManager.GetString("lblCareerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Ar.
        /// </summary>
        public static string lblCityAr {
            get {
                return ResourceManager.GetString("lblCityAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City En.
        /// </summary>
        public static string lblCityEn {
            get {
                return ResourceManager.GetString("lblCityEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Title Ar.
        /// </summary>
        public static string lblCMSTitleAr {
            get {
                return ResourceManager.GetString("lblCMSTitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Title En.
        /// </summary>
        public static string lblCMSTitleEn {
            get {
                return ResourceManager.GetString("lblCMSTitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string lblComments {
            get {
                return ResourceManager.GetString("lblComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string lblContact {
            get {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string lblContactNo {
            get {
                return ResourceManager.GetString("lblContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Ar.
        /// </summary>
        public static string lblContentAr {
            get {
                return ResourceManager.GetString("lblContentAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content En.
        /// </summary>
        public static string lblContentEn {
            get {
                return ResourceManager.GetString("lblContentEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Management.
        /// </summary>
        public static string lblContentManagement {
            get {
                return ResourceManager.GetString("lblContentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magzine Cover.
        /// </summary>
        public static string lblCoverDoc {
            get {
                return ResourceManager.GetString("lblCoverDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string lblCreatedDate {
            get {
                return ResourceManager.GetString("lblCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string lblDateOfBirth {
            get {
                return ResourceManager.GetString("lblDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Ar.
        /// </summary>
        public static string lblDescriptionAr {
            get {
                return ResourceManager.GetString("lblDescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description En.
        /// </summary>
        public static string lblDescriptionEn {
            get {
                return ResourceManager.GetString("lblDescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Skill Ar.
        /// </summary>
        public static string lblDesiredSkillAr {
            get {
                return ResourceManager.GetString("lblDesiredSkillAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Skills En.
        /// </summary>
        public static string lblDesiredSkillsEn {
            get {
                return ResourceManager.GetString("lblDesiredSkillsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string lblDocument {
            get {
                return ResourceManager.GetString("lblDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Text Ar.
        /// </summary>
        public static string lblDocumentTextAr {
            get {
                return ResourceManager.GetString("lblDocumentTextAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Text En.
        /// </summary>
        public static string lblDocumentTextEn {
            get {
                return ResourceManager.GetString("lblDocumentTextEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string lblEducation {
            get {
                return ResourceManager.GetString("lblEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Content.
        /// </summary>
        public static string lblEmailContent {
            get {
                return ResourceManager.GetString("lblEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email From.
        /// </summary>
        public static string lblEmailFrom {
            get {
                return ResourceManager.GetString("lblEmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template En.
        /// </summary>
        public static string lblEmailTemplate {
            get {
                return ResourceManager.GetString("lblEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template Ar.
        /// </summary>
        public static string lblEmailTemplateAr {
            get {
                return ResourceManager.GetString("lblEmailTemplateAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string lblEndDate {
            get {
                return ResourceManager.GetString("lblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string lblEvents {
            get {
                return ResourceManager.GetString("lblEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        public static string lblEventType {
            get {
                return ResourceManager.GetString("lblEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string lblExcel {
            get {
                return ResourceManager.GetString("lblExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File.
        /// </summary>
        public static string lblExcelDoc {
            get {
                return ResourceManager.GetString("lblExcelDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Logo.
        /// </summary>
        public static string lblExcelLogo {
            get {
                return ResourceManager.GetString("lblExcelLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string lblExperience {
            get {
                return ResourceManager.GetString("lblExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string lblFacebook {
            get {
                return ResourceManager.GetString("lblFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string lblFAQ {
            get {
                return ResourceManager.GetString("lblFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        public static string lblFAQs {
            get {
                return ResourceManager.GetString("lblFAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string lblFax {
            get {
                return ResourceManager.GetString("lblFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string lblFileDocument {
            get {
                return ResourceManager.GetString("lblFileDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string lblFullName {
            get {
                return ResourceManager.GetString("lblFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Address.
        /// </summary>
        public static string lblHomeAddress {
            get {
                return ResourceManager.GetString("lblHomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry.
        /// </summary>
        public static string lblInquiry {
            get {
                return ResourceManager.GetString("lblInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string lblInstagram {
            get {
                return ResourceManager.GetString("lblInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iphone App Link.
        /// </summary>
        public static string lblIphoneLink {
            get {
                return ResourceManager.GetString("lblIphoneLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iphone Logo.
        /// </summary>
        public static string lblIphoneLogo {
            get {
                return ResourceManager.GetString("lblIphoneLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iphone QR Image.
        /// </summary>
        public static string lblIphoneQRImage {
            get {
                return ResourceManager.GetString("lblIphoneQRImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Applied.
        /// </summary>
        public static string lblJobApplied {
            get {
                return ResourceManager.GetString("lblJobApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string lblLatitude {
            get {
                return ResourceManager.GetString("lblLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Ar.
        /// </summary>
        public static string lblLocationAr {
            get {
                return ResourceManager.GetString("lblLocationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Ar.
        /// </summary>
        public static string lblLocationArabic {
            get {
                return ResourceManager.GetString("lblLocationArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location En.
        /// </summary>
        public static string lblLocationEn {
            get {
                return ResourceManager.GetString("lblLocationEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location En.
        /// </summary>
        public static string lblLocationEnglish {
            get {
                return ResourceManager.GetString("lblLocationEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string lblLogo {
            get {
                return ResourceManager.GetString("lblLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string lblLongitude {
            get {
                return ResourceManager.GetString("lblLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magzines.
        /// </summary>
        public static string lblMagzine {
            get {
                return ResourceManager.GetString("lblMagzine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Banner.
        /// </summary>
        public static string lblMainBanner {
            get {
                return ResourceManager.GetString("lblMainBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string lblMaritalStatus {
            get {
                return ResourceManager.GetString("lblMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Description Ar.
        /// </summary>
        public static string lblMetaDescAr {
            get {
                return ResourceManager.GetString("lblMetaDescAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Description En.
        /// </summary>
        public static string lblMetaDescEn {
            get {
                return ResourceManager.GetString("lblMetaDescEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Description Ar.
        /// </summary>
        public static string lblMetaDescriptionAr {
            get {
                return ResourceManager.GetString("lblMetaDescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Keywords Ar.
        /// </summary>
        public static string lblMetaKeywordsAr {
            get {
                return ResourceManager.GetString("lblMetaKeywordsAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Keywords En.
        /// </summary>
        public static string lblMetaKeywordsEn {
            get {
                return ResourceManager.GetString("lblMetaKeywordsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Title Ar.
        /// </summary>
        public static string lblMetaTitleAr {
            get {
                return ResourceManager.GetString("lblMetaTitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Title En.
        /// </summary>
        public static string lblMetaTitleEn {
            get {
                return ResourceManager.GetString("lblMetaTitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Education Ar.
        /// </summary>
        public static string lblMinEductaionAr {
            get {
                return ResourceManager.GetString("lblMinEductaionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Experience Ar.
        /// </summary>
        public static string lblMinExperienceAr {
            get {
                return ResourceManager.GetString("lblMinExperienceAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Education En.
        /// </summary>
        public static string lblMinimumEducationEn {
            get {
                return ResourceManager.GetString("lblMinimumEducationEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Experience En.
        /// </summary>
        public static string lblMinimumExperienceEn {
            get {
                return ResourceManager.GetString("lblMinimumExperienceEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblMobile.
        /// </summary>
        public static string lblMobile {
            get {
                return ResourceManager.GetString("lblMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string lblMobilePhoneNumber {
            get {
                return ResourceManager.GetString("lblMobilePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name Ar.
        /// </summary>
        public static string lblNameAr {
            get {
                return ResourceManager.GetString("lblNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Ar.
        /// </summary>
        public static string lblNameArabic {
            get {
                return ResourceManager.GetString("lblNameArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name En.
        /// </summary>
        public static string lblNameEn {
            get {
                return ResourceManager.GetString("lblNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name En.
        /// </summary>
        public static string lblNameEnglish {
            get {
                return ResourceManager.GetString("lblNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string lblNationality {
            get {
                return ResourceManager.GetString("lblNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string lblNews {
            get {
                return ResourceManager.GetString("lblNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Ar.
        /// </summary>
        public static string lblNotesArabic {
            get {
                return ResourceManager.GetString("lblNotesArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes En.
        /// </summary>
        public static string lblNotesEnglish {
            get {
                return ResourceManager.GetString("lblNotesEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office No.
        /// </summary>
        public static string lblOfficePhoneNo {
            get {
                return ResourceManager.GetString("lblOfficePhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Content Ar.
        /// </summary>
        public static string lblPageContentAr {
            get {
                return ResourceManager.GetString("lblPageContentAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name.
        /// </summary>
        public static string lblPageName {
            get {
                return ResourceManager.GetString("lblPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Ar.
        /// </summary>
        public static string lblPageNameAr {
            get {
                return ResourceManager.GetString("lblPageNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name En.
        /// </summary>
        public static string lblPageNameEn {
            get {
                return ResourceManager.GetString("lblPageNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name.
        /// </summary>
        public static string lblParentName {
            get {
                return ResourceManager.GetString("lblParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string lblParentPage {
            get {
                return ResourceManager.GetString("lblParentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string lblPDF {
            get {
                return ResourceManager.GetString("lblPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF File.
        /// </summary>
        public static string lblPDFDoc {
            get {
                return ResourceManager.GetString("lblPDFDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Logo.
        /// </summary>
        public static string lblPDFLogo {
            get {
                return ResourceManager.GetString("lblPDFLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Email.
        /// </summary>
        public static string lblPersonEmail {
            get {
                return ResourceManager.GetString("lblPersonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Name.
        /// </summary>
        public static string lblPersonName {
            get {
                return ResourceManager.GetString("lblPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Store URL.
        /// </summary>
        public static string lblPlayStoreURL {
            get {
                return ResourceManager.GetString("lblPlayStoreURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Box.
        /// </summary>
        public static string lblPOBox {
            get {
                return ResourceManager.GetString("lblPOBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Date.
        /// </summary>
        public static string lblPublicationData {
            get {
                return ResourceManager.GetString("lblPublicationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string lblRating {
            get {
                return ResourceManager.GetString("lblRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference #.
        /// </summary>
        public static string lblRefNo {
            get {
                return ResourceManager.GetString("lblRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibilities Ar.
        /// </summary>
        public static string lblResponsibilitiesAr {
            get {
                return ResourceManager.GetString("lblResponsibilitiesAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibilities En.
        /// </summary>
        public static string lblResponsibilitiesEn {
            get {
                return ResourceManager.GetString("lblResponsibilitiesEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblRowStatus {
            get {
                return ResourceManager.GetString("lblRowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Ar.
        /// </summary>
        public static string lblSalaryAr {
            get {
                return ResourceManager.GetString("lblSalaryAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Ar.
        /// </summary>
        public static string lblSalaryCurrencyAr {
            get {
                return ResourceManager.GetString("lblSalaryCurrencyAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency En.
        /// </summary>
        public static string lblSalaryCurrencyEn {
            get {
                return ResourceManager.GetString("lblSalaryCurrencyEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary En.
        /// </summary>
        public static string lblSalaryEn {
            get {
                return ResourceManager.GetString("lblSalaryEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Email.
        /// </summary>
        public static string lblSenderEmail {
            get {
                return ResourceManager.GetString("lblSenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Name.
        /// </summary>
        public static string lblSenderName {
            get {
                return ResourceManager.GetString("lblSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Ar.
        /// </summary>
        public static string lblShiftAr {
            get {
                return ResourceManager.GetString("lblShiftAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift En.
        /// </summary>
        public static string lblShiftEn {
            get {
                return ResourceManager.GetString("lblShiftEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        public static string lblSiteMap {
            get {
                return ResourceManager.GetString("lblSiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Settings.
        /// </summary>
        public static string lblSiteSettings {
            get {
                return ResourceManager.GetString("lblSiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string lblSkills {
            get {
                return ResourceManager.GetString("lblSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standalone.
        /// </summary>
        public static string lblStandalone {
            get {
                return ResourceManager.GetString("lblStandalone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string lblSubject {
            get {
                return ResourceManager.GetString("lblSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Ar.
        /// </summary>
        public static string lblSubjectAr {
            get {
                return ResourceManager.GetString("lblSubjectAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject En.
        /// </summary>
        public static string lblSubjectEn {
            get {
                return ResourceManager.GetString("lblSubjectEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Type.
        /// </summary>
        public static string lblSubscriptionType {
            get {
                return ResourceManager.GetString("lblSubscriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string lblSummary {
            get {
                return ResourceManager.GetString("lblSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Category.
        /// </summary>
        public static string lblSupportCategory {
            get {
                return ResourceManager.GetString("lblSupportCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Ar.
        /// </summary>
        public static string lblThemeArabic {
            get {
                return ResourceManager.GetString("lblThemeArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme En.
        /// </summary>
        public static string lblThemeEnglish {
            get {
                return ResourceManager.GetString("lblThemeEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Ar.
        /// </summary>
        public static string lblTitleAr {
            get {
                return ResourceManager.GetString("lblTitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title En.
        /// </summary>
        public static string lblTitleEn {
            get {
                return ResourceManager.GetString("lblTitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Tip Ar.
        /// </summary>
        public static string lblToolTipAr {
            get {
                return ResourceManager.GetString("lblToolTipAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Tip En.
        /// </summary>
        public static string lblToolTipEn {
            get {
                return ResourceManager.GetString("lblToolTipEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Program.
        /// </summary>
        public static string lblTrainingProgram {
            get {
                return ResourceManager.GetString("lblTrainingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string lblTwitter {
            get {
                return ResourceManager.GetString("lblTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string lblURL {
            get {
                return ResourceManager.GetString("lblURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type.
        /// </summary>
        public static string lblUserType {
            get {
                return ResourceManager.GetString("lblUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string lblVideo {
            get {
                return ResourceManager.GetString("lblVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video URL.
        /// </summary>
        public static string lblVideoURL {
            get {
                return ResourceManager.GetString("lblVideoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string lblWebsite {
            get {
                return ResourceManager.GetString("lblWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows App QR Image.
        /// </summary>
        public static string lblWindowsQRImage {
            get {
                return ResourceManager.GetString("lblWindowsQRImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Store URL.
        /// </summary>
        public static string lblWinStoreURL {
            get {
                return ResourceManager.GetString("lblWinStoreURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string lblWord {
            get {
                return ResourceManager.GetString("lblWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Logo.
        /// </summary>
        public static string lblWordLogo {
            get {
                return ResourceManager.GetString("lblWordLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours Ar.
        /// </summary>
        public static string lblWorkingHoursAr {
            get {
                return ResourceManager.GetString("lblWorkingHoursAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours En.
        /// </summary>
        public static string lblWorkingHoursEn {
            get {
                return ResourceManager.GetString("lblWorkingHoursEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Place.
        /// </summary>
        public static string lblWorkplace {
            get {
                return ResourceManager.GetString("lblWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string lblYoutube {
            get {
                return ResourceManager.GetString("lblYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links Management.
        /// </summary>
        public static string LinksManagement {
            get {
                return ResourceManager.GetString("LinksManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magzines.
        /// </summary>
        public static string Magzines {
            get {
                return ResourceManager.GetString("Magzines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Career Industry.
        /// </summary>
        public static string ManageCareerIndustry {
            get {
                return ResourceManager.GetString("ManageCareerIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Contact.
        /// </summary>
        public static string ManageContact {
            get {
                return ResourceManager.GetString("ManageContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Help.
        /// </summary>
        public static string ManageHelp {
            get {
                return ResourceManager.GetString("ManageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Open Data.
        /// </summary>
        public static string ManageOpenData {
            get {
                return ResourceManager.GetString("ManageOpenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Projects.
        /// </summary>
        public static string ManageProjects {
            get {
                return ResourceManager.GetString("ManageProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Applications.
        /// </summary>
        public static string MobileApplications {
            get {
                return ResourceManager.GetString("MobileApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Participation Policy.
        /// </summary>
        public static string ParticipationPolicy {
            get {
                return ResourceManager.GetString("ParticipationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Services.
        /// </summary>
        public static string PartnerServices {
            get {
                return ResourceManager.GetString("PartnerServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polls.
        /// </summary>
        public static string Polls {
            get {
                return ResourceManager.GetString("Polls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated sucessfully.
        /// </summary>
        public static string RecordUpdatedSucessfully {
            get {
                return ResourceManager.GetString("RecordUpdatedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules &amp; Regulations.
        /// </summary>
        public static string RulesAndRegulations {
            get {
                return ResourceManager.GetString("RulesAndRegulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        public static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Settings.
        /// </summary>
        public static string SiteSettings {
            get {
                return ResourceManager.GetString("SiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions Management.
        /// </summary>
        public static string SubscriptionsManagement {
            get {
                return ResourceManager.GetString("SubscriptionsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Request.
        /// </summary>
        public static string SupportRequest {
            get {
                return ResourceManager.GetString("SupportRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Plans.
        /// </summary>
        public static string TrainingPlans {
            get {
                return ResourceManager.GetString("TrainingPlans", resourceCulture);
            }
        }
    }
}
