//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant_Category
    {
        public Applicant_Category()
        {
            this.Applicant_Category1 = new HashSet<Applicant_Category>();
            this.Applicant_Content_Category = new HashSet<Applicant_Content_Category>();
            this.City_Description = new HashSet<City_Description>();
        }
    
        public long Applicant_Category_Id { get; set; }
        public string Category_Name_En { get; set; }
        public string Category_Name_Ar { get; set; }
        public Nullable<long> Parent_Id { get; set; }
        public string Header_Description_En { get; set; }
        public string Header_Description_Ar { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual ICollection<Applicant_Category> Applicant_Category1 { get; set; }
        public virtual Applicant_Category Applicant_Category2 { get; set; }
        public virtual ICollection<Applicant_Content_Category> Applicant_Content_Category { get; set; }
        public virtual ICollection<City_Description> City_Description { get; set; }
    }
}
