//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career_Job
    {
        public Career_Job()
        {
            this.Career_Job_Document = new HashSet<Career_Job_Document>();
            this.Career_Job_Applied = new HashSet<Career_Job_Applied>();
        }
    
        public long Career_Job_Id { get; set; }
        public Nullable<long> Career_Industry_Id { get; set; }
        public Nullable<long> Career_Type_Id { get; set; }
        public string Title_Ar { get; set; }
        public string Description_Ar { get; set; }
        public string Location_Ar { get; set; }
        public string Salary_Ar { get; set; }
        public string Salary_Currency_Ar { get; set; }
        public string Minumum_Eduction_Ar { get; set; }
        public string Minumum_Experience_Ar { get; set; }
        public string Desired_Skills_Ar { get; set; }
        public string Benefits_Ar { get; set; }
        public string Responsibilities_Ar { get; set; }
        public string Shift_Ar { get; set; }
        public string Title_En { get; set; }
        public string Description_En { get; set; }
        public string Location_En { get; set; }
        public string Salary_En { get; set; }
        public string Salary_Currency_En { get; set; }
        public string Minumum_Eduction_En { get; set; }
        public string Minumum_Experience_En { get; set; }
        public string Desired_Skills_En { get; set; }
        public string Benefits_En { get; set; }
        public string Responsibilities_En { get; set; }
        public string Shift_En { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual Career_Industry Career_Industry { get; set; }
        public virtual ICollection<Career_Job_Document> Career_Job_Document { get; set; }
        public virtual Career_Type Career_Type { get; set; }
        public virtual ICollection<Career_Job_Applied> Career_Job_Applied { get; set; }
    }
}
