//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITJCMSEntities : DbContext
    {
        public ITJCMSEntities()
            : base("name=ITJCMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Banner_Documents> Banner_Documents { get; set; }
        public virtual DbSet<Career_Industry> Career_Industry { get; set; }
        public virtual DbSet<Career_Job> Career_Job { get; set; }
        public virtual DbSet<Career_Job_Applied> Career_Job_Applied { get; set; }
        public virtual DbSet<Career_Job_Document> Career_Job_Document { get; set; }
        public virtual DbSet<Career_Type> Career_Type { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Event_Document> Event_Document { get; set; }
        public virtual DbSet<Event_Type> Event_Type { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<FAQ_Category> FAQ_Category { get; set; }
        public virtual DbSet<File_Types> File_Types { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<Link_Document> Link_Document { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<News_Documents> News_Documents { get; set; }
        public virtual DbSet<Page_Menu> Page_Menu { get; set; }
        public virtual DbSet<Row_Statuses> Row_Statuses { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Subscriber> Subscribers { get; set; }
        public virtual DbSet<Subscription_Type> Subscription_Type { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<Survey_Question> Survey_Question { get; set; }
        public virtual DbSet<Survey_Question_Answer> Survey_Question_Answer { get; set; }
        public virtual DbSet<Survey_Question_Option> Survey_Question_Option { get; set; }
        public virtual DbSet<Training_Plan> Training_Plan { get; set; }
        public virtual DbSet<Training_Program> Training_Program { get; set; }
        public virtual DbSet<News_Category> News_Category { get; set; }
        public virtual DbSet<Research_Study> Research_Study { get; set; }
        public virtual DbSet<Research_Study_Category> Research_Study_Category { get; set; }
        public virtual DbSet<Canned_Email_Documents> Canned_Email_Documents { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Mobile_App> Mobile_App { get; set; }
        public virtual DbSet<Partner_Service> Partner_Service { get; set; }
        public virtual DbSet<Site_Map> Site_Map { get; set; }
        public virtual DbSet<Help> Helps { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<Form_Documents> Form_Documents { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Open_Data> Open_Data { get; set; }
        public virtual DbSet<Rules_And_Regulation> Rules_And_Regulation { get; set; }
        public virtual DbSet<Contact_Chairman> Contact_Chairman { get; set; }
        public virtual DbSet<Technical_Support_Category> Technical_Support_Category { get; set; }
        public virtual DbSet<Technical_Support_Request> Technical_Support_Request { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
        public virtual DbSet<Magzine> Magzines { get; set; }
        public virtual DbSet<E_Participation> E_Participation { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Contact_Us> Contact_Us { get; set; }
        public virtual DbSet<E_Service_Category> E_Service_Category { get; set; }
        public virtual DbSet<E_Services> E_Services { get; set; }
        public virtual DbSet<Call_Center_Polling> Call_Center_Polling { get; set; }
        public virtual DbSet<Conditions_And_Requirements> Conditions_And_Requirements { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Home_Setting> Home_Setting { get; set; }
        public virtual DbSet<Canned_Email> Canned_Email { get; set; }
        public virtual DbSet<Happiness_Meter> Happiness_Meter { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
        public virtual DbSet<PollOption> PollOptions { get; set; }
        public virtual DbSet<User_Votes> User_Votes { get; set; }
        public virtual DbSet<Feed_Back> Feed_Back { get; set; }
        public virtual DbSet<Social_Media> Social_Media { get; set; }
        public virtual DbSet<Applicant_Category> Applicant_Category { get; set; }
        public virtual DbSet<Applicant_Content_Category> Applicant_Content_Category { get; set; }
        public virtual DbSet<Applicant_Content_Sub_Category> Applicant_Content_Sub_Category { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<City_Description> City_Description { get; set; }
    }
}
