//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.Banner_Documents = new HashSet<Banner_Documents>();
            this.Career_Job_Document = new HashSet<Career_Job_Document>();
            this.News_Documents = new HashSet<News_Documents>();
            this.Event_Document = new HashSet<Event_Document>();
            this.Galleries = new HashSet<Gallery>();
            this.Link_Document = new HashSet<Link_Document>();
            this.Settings = new HashSet<Setting>();
            this.Research_Study = new HashSet<Research_Study>();
            this.Canned_Email_Documents = new HashSet<Canned_Email_Documents>();
            this.Career_Job_Applied = new HashSet<Career_Job_Applied>();
            this.Mobile_App = new HashSet<Mobile_App>();
            this.Mobile_App1 = new HashSet<Mobile_App>();
            this.Mobile_App2 = new HashSet<Mobile_App>();
            this.Mobile_App3 = new HashSet<Mobile_App>();
            this.Mobile_App4 = new HashSet<Mobile_App>();
            this.Partner_Service = new HashSet<Partner_Service>();
            this.Form_Documents = new HashSet<Form_Documents>();
            this.Projects = new HashSet<Project>();
            this.Open_Data = new HashSet<Open_Data>();
            this.Open_Data1 = new HashSet<Open_Data>();
            this.Rules_And_Regulation = new HashSet<Rules_And_Regulation>();
            this.Technical_Support_Request = new HashSet<Technical_Support_Request>();
            this.Magzines = new HashSet<Magzine>();
            this.Magzines1 = new HashSet<Magzine>();
            this.E_Participation = new HashSet<E_Participation>();
            this.E_Services = new HashSet<E_Services>();
            this.Pages = new HashSet<Page>();
            this.Home_Setting = new HashSet<Home_Setting>();
            this.Home_Setting1 = new HashSet<Home_Setting>();
            this.Home_Setting2 = new HashSet<Home_Setting>();
            this.Home_Setting3 = new HashSet<Home_Setting>();
            this.Social_Media = new HashSet<Social_Media>();
        }
    
        public long Document_Id { get; set; }
        public Nullable<long> File_Type_Id { get; set; }
        public string File_Name { get; set; }
        public string Extenstion { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual ICollection<Banner_Documents> Banner_Documents { get; set; }
        public virtual ICollection<Career_Job_Document> Career_Job_Document { get; set; }
        public virtual ICollection<News_Documents> News_Documents { get; set; }
        public virtual ICollection<Event_Document> Event_Document { get; set; }
        public virtual ICollection<Gallery> Galleries { get; set; }
        public virtual ICollection<Link_Document> Link_Document { get; set; }
        public virtual ICollection<Setting> Settings { get; set; }
        public virtual ICollection<Research_Study> Research_Study { get; set; }
        public virtual ICollection<Canned_Email_Documents> Canned_Email_Documents { get; set; }
        public virtual ICollection<Career_Job_Applied> Career_Job_Applied { get; set; }
        public virtual ICollection<Mobile_App> Mobile_App { get; set; }
        public virtual ICollection<Mobile_App> Mobile_App1 { get; set; }
        public virtual ICollection<Mobile_App> Mobile_App2 { get; set; }
        public virtual ICollection<Mobile_App> Mobile_App3 { get; set; }
        public virtual ICollection<Mobile_App> Mobile_App4 { get; set; }
        public virtual ICollection<Partner_Service> Partner_Service { get; set; }
        public virtual ICollection<Form_Documents> Form_Documents { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Open_Data> Open_Data { get; set; }
        public virtual ICollection<Open_Data> Open_Data1 { get; set; }
        public virtual ICollection<Rules_And_Regulation> Rules_And_Regulation { get; set; }
        public virtual ICollection<Technical_Support_Request> Technical_Support_Request { get; set; }
        public virtual ICollection<Magzine> Magzines { get; set; }
        public virtual ICollection<Magzine> Magzines1 { get; set; }
        public virtual ICollection<E_Participation> E_Participation { get; set; }
        public virtual ICollection<E_Services> E_Services { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
        public virtual ICollection<Home_Setting> Home_Setting { get; set; }
        public virtual ICollection<Home_Setting> Home_Setting1 { get; set; }
        public virtual ICollection<Home_Setting> Home_Setting2 { get; set; }
        public virtual ICollection<Home_Setting> Home_Setting3 { get; set; }
        public virtual ICollection<Social_Media> Social_Media { get; set; }
    }
}
