//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Event_Document = new HashSet<Event_Document>();
        }
    
        public long Event_Id { get; set; }
        public Nullable<long> Event_Type_Id { get; set; }
        public string Title_Ar { get; set; }
        public string Description_Ar { get; set; }
        public string Title_En { get; set; }
        public string Description_En { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Location_Ar { get; set; }
        public string Location_En { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual ICollection<Event_Document> Event_Document { get; set; }
        public virtual Event_Type Event_Type { get; set; }
    }
}
