//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magzine
    {
        public long Magzine_Id { get; set; }
        public string Title_En { get; set; }
        public string Title_Ar { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> File_Document_Id { get; set; }
        public Nullable<long> Cover_Document_Id { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Document Document1 { get; set; }
    }
}
