//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.Page1 = new HashSet<Page>();
            this.Page_Menu = new HashSet<Page_Menu>();
        }
    
        public long Page_Id { get; set; }
        public string Page_Name_En { get; set; }
        public string Page_Content_En { get; set; }
        public Nullable<long> Parent_Id { get; set; }
        public string Meta_Title_En { get; set; }
        public string Meta_Keywords_En { get; set; }
        public string Meta_Description_En { get; set; }
        public Nullable<bool> IsStandalone { get; set; }
        public string Page_Name_Ar { get; set; }
        public string Page_Content_Ar { get; set; }
        public string Meta_Title_Ar { get; set; }
        public string Meta_Keywords_Ar { get; set; }
        public string Meta_Description_Ar { get; set; }
        public string Url { get; set; }
        public Nullable<long> Document_Id { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual ICollection<Page> Page1 { get; set; }
        public virtual Page Page2 { get; set; }
        public virtual ICollection<Page_Menu> Page_Menu { get; set; }
    }
}
