//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollOption
    {
        public PollOption()
        {
            this.User_Votes = new HashSet<User_Votes>();
        }
    
        public long Poll_Option_Id { get; set; }
        public string Option_En { get; set; }
        public string Option_Ar { get; set; }
        public Nullable<long> Poll_Id { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual Poll Poll { get; set; }
        public virtual ICollection<User_Votes> User_Votes { get; set; }
    }
}
