//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Map
    {
        public Site_Map()
        {
            this.Site_Map1 = new HashSet<Site_Map>();
        }
    
        public long Site_Map_Id { get; set; }
        public string Name_En { get; set; }
        public string Name_Ar { get; set; }
        public string URL { get; set; }
        public Nullable<long> Parent_Id { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual ICollection<Site_Map> Site_Map1 { get; set; }
        public virtual Site_Map Site_Map2 { get; set; }
    }
}
