//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Social_Media
    {
        public long Social_Media_Id { get; set; }
        public string Title_En { get; set; }
        public string Title_Ar { get; set; }
        public string Url { get; set; }
        public Nullable<long> Document_Id { get; set; }
        public string Tool_Tip_En { get; set; }
        public string Tool_Tip_Ar { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
