//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey_Question_Answer
    {
        public long Survey_Question_Answer_Id { get; set; }
        public Nullable<long> Survery_Id { get; set; }
        public Nullable<long> Survey_Question_Id { get; set; }
        public Nullable<long> Surver_Question_Option_Id { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual Survey Survey { get; set; }
        public virtual Survey_Question Survey_Question { get; set; }
        public virtual Survey_Question_Option Survey_Question_Option { get; set; }
    }
}
