//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technical_Support_Request
    {
        public long Technical_Support_Id { get; set; }
        public string Reference_No { get; set; }
        public string Person_Name { get; set; }
        public string Person_Mobile_No { get; set; }
        public string Person_Email_Id { get; set; }
        public Nullable<long> User_Type_Id { get; set; }
        public Nullable<long> Technical_Support_Category_Id { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public Nullable<long> Document_Id { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual Technical_Support_Category Technical_Support_Category { get; set; }
        public virtual User_Type User_Type { get; set; }
        public virtual Document Document { get; set; }
    }
}
