//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training_Program
    {
        public Training_Program()
        {
            this.Training_Plan = new HashSet<Training_Plan>();
        }
    
        public long Training_Program_Id { get; set; }
        public string Name_Ar { get; set; }
        public string Description_Ar { get; set; }
        public string Name_En { get; set; }
        public string Description_En { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual ICollection<Training_Plan> Training_Plan { get; set; }
    }
}
