//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training_Plan
    {
        public long Training_Plan_Id { get; set; }
        public Nullable<long> Training_Program_Id { get; set; }
        public string Location_Ar { get; set; }
        public string Theme_Ar { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Audience_Ar { get; set; }
        public string Notes_Ar { get; set; }
        public string Location_En { get; set; }
        public string Audience_En { get; set; }
        public string Notes_En { get; set; }
        public string Theme_En { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Row_Status_Id { get; set; }
    
        public virtual Training_Program Training_Program { get; set; }
    }
}
